# Generated by Django 4.2 on 2025-10-04 04:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("loanpro", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("suspended", "Suspended"),
                ],
                default="pending",
                help_text="Account approval status for self-registered customers",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who made the customer assignment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_assignments_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="assigned_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when customer was assigned to staff",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="assigned_staff",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member assigned to manage this customer relationship",
                limit_choices_to={
                    "role__in": ["manager", "relationship_officer", "account_officer"]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_customers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="account_number",
            field=models.CharField(
                blank=True,
                help_text="Unique account number generated automatically",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="account_type",
            field=models.CharField(
                choices=[("individual", "Individual"), ("business", "Business")],
                help_text="Type of customer account (individual or business)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(
                help_text="Customer's physical address for verification purposes"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the customer account was created",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_by",
            field=models.ForeignKey(
                help_text="Staff member who created this customer account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_customers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="credit_score",
            field=models.IntegerField(
                default=300,
                help_text="Customer credit score (300-850) used for loan risk assessment",
                validators=[
                    django.core.validators.MinValueValidator(300),
                    django.core.validators.MaxValueValidator(850),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="current_borrow_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Current maximum amount the customer can borrow",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="is_address_verified",
            field=models.BooleanField(
                default=False,
                help_text="Whether the customer's address has been verified",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="tier",
            field=models.IntegerField(
                choices=[
                    (1, "Tier 1 - Basic verification"),
                    (2, "Tier 2 - Additional verification"),
                    (3, "Tier 3 - Advanced verification"),
                    (4, "Tier 4 - Full verification"),
                ],
                default=1,
                help_text="Customer verification tier (1-4) determining borrowing limits",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when the customer account was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                help_text="Associated user account for authentication and basic info",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="customer",
            field=models.ForeignKey(
                help_text="Customer who owns this document",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="loanpro.customer",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("id", "ID Card"),
                    ("photo", "Passport Photo"),
                    ("proof_of_address", "Proof of Address"),
                    ("cac_docs", "CAC Documents"),
                    ("tax_id", "Tax ID"),
                    ("financial_statements", "Financial Statements"),
                    ("bank_statement", "Bank Statement"),
                    ("business_license", "Business License"),
                ],
                help_text="Type of document from predefined choices",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_path",
            field=models.CharField(
                help_text="Path or URL where the document file is stored",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Whether this document has been verified by staff",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the document was uploaded"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                help_text="Staff member who uploaded this document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Principal loan amount requested by the customer",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who approved the loan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the loan application was created",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="customer",
            field=models.ForeignKey(
                help_text="Customer who applied for this loan",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="loanpro.customer",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="disbursed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the loan funds were disbursed",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="due_date",
            field=models.DateField(
                blank=True, help_text="Final due date for loan completion", null=True
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="duration_months",
            field=models.IntegerField(help_text="Loan term duration in months"),
        ),
        migrations.AlterField(
            model_name="loan",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the loan",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=15.0,
                help_text="Annual interest rate percentage (default 15%)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="requested_by",
            field=models.ForeignKey(
                help_text="User who submitted the loan application",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("disbursed", "Disbursed"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("defaulted", "Defaulted"),
                ],
                default="pending",
                help_text="Current status of the loan in its lifecycle",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the loan was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the user account was created",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_phone_verified",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user's phone number has been verified via OTP",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="User's phone number for verification and notifications",
                max_length=15,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("relationship_officer", "Relationship Officer"),
                    ("account_officer", "Account Officer"),
                    ("customer", "Customer"),
                ],
                help_text="User's role determining their access level and permissions",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when the user account was last updated",
            ),
        ),
        migrations.CreateModel(
            name="KYCVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bvn",
                    models.CharField(
                        blank=True,
                        help_text="11-digit Bank Verification Number for financial identity verification",
                        max_length=11,
                        null=True,
                    ),
                ),
                (
                    "nin",
                    models.CharField(
                        blank=True,
                        help_text="11-digit National Identity Number for government identity verification",
                        max_length=11,
                        null=True,
                    ),
                ),
                (
                    "bvn_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the BVN has been successfully verified",
                    ),
                ),
                (
                    "nin_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the NIN has been successfully verified",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("in_progress", "Verification In Progress"),
                            ("verified", "Fully Verified"),
                            ("rejected", "Verification Rejected"),
                            ("incomplete", "Incomplete Information"),
                        ],
                        default="pending",
                        help_text="Overall KYC verification status",
                        max_length=20,
                    ),
                ),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when KYC verification was completed",
                        null=True,
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the verification process or any issues",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the KYC verification record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the KYC verification record was last updated",
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        help_text="Customer associated with this KYC verification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_verification",
                        to="loanpro.customer",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who performed the KYC verification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_kyc_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "KYC Verification",
                "verbose_name_plural": "KYC Verifications",
            },
        ),
    ]
